name: "publish ğŸš€"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: publish ğŸš€
    runs-on: ubuntu-latest
    steps:
      - name: checkout âœ…
        uses: actions/checkout@v2.1.1
      - name: node ğŸŸ¢
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: building ğŸ”©
        run: ng build --prod
      - name: publishing ğŸš€
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
